### ISSUE TITLE
LinkError: post-link script failed for package conda-forge::cudatoolkit-dev-11.7.0-h9f2f4db_6

### ISSUE THREAD

**Issue by CRCODE22** [ltngonnguyen/vicuna-matata#3]
(vicuna-matata) D:\>conda install -c conda-forge cudatoolkit-dev
Collecting package metadata (current_repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: C:\Users\CRCODE22\.conda\envs\vicuna-matata

  added / updated specs:
    - cudatoolkit-dev

The following NEW packages will be INSTALLED:

  7zip               conda-forge/win-64::7zip-19.00-h2d74725_2
  cudatoolkit-dev    conda-forge/win-64::cudatoolkit-dev-11.7.0-h9f2f4db_6

Proceed ([y]/n)? y

Downloading and Extracting Packages

Preparing transaction: done
Verifying transaction: done
Executing transaction: done
ERROR conda.core.link:_execute(740): An error occurred while installing package 'conda-forge::cudatoolkit-dev-11.7.0-h9f2f4db_6'.
Rolling back transaction: done

LinkError: post-link script failed for package conda-forge::cudatoolkit-dev-11.7.0-h9f2f4db_6
location of failed script: C:\Users\CRCODE22\.conda\envs\vicuna-matata\Scripts\.cudatoolkit-dev-post-link.bat
==> script messages <==
<None>
==> script output <==
stdout:
stderr: The system cannot find the path specified.

return code: 1

()

**Comment by ltngonnguyen** [comment]
Are you using WSL or Windows? The guide is geared towards Linux so I really have no idea if it will work on Windows or not. Try this guide for Windows: https://www.youtube.com/watch?v=ByV5w1ES38A&t=2s
